run_name = "miniDDP_8M_batch_size_per_device=8_seq_len=1024_steps=1000"

[model]
vocab_size = 50257
d_model = 128
max_seq_len = 1024
n_layers = 8
d_head = 16
n_heads = 8
ffn_in = 512

[trainer]
seed = 42
device_id = 3
eval_every_step = -1
per_device_batch_size = 8

[data]
train_tokens_path = "data/preprocessed/tinystories_train.bin"
val_tokens_path = "data/preprocessed/tinystories_val.bin"
num_workers = 4

[optim]
type = "adam"
lr = "1e-3"

[runtime]
name = "ddp_reference"
