run_name = "testing_out_ddp1"

[model]
vocab_size = 50257
d_model = 128
max_seq_len = 128
n_layers = 2
d_head = 16
n_heads = 8
ffn_in = 128

[trainer]
device_id = 3
eval_every_step = 500
per_device_batch_size = 2

[data]
train_tokens_path = "data/preprocessed/tinystories_train.bin"
val_tokens_path = "data/preprocessed/tinystories_val.bin"
num_workers = 4

[optim]
type = "adam"
lr = "1e-3"

[runtime]
name = "single"
